### ISSUE TITLE
The last ">" is not colored correctly when you create a new instance of generics type whose namespace has periods

### ISSUE THREAD

**Issue by ryonakano** [thiagoabreu/vala-code#13]
![Screenshot from 2019-05-10 19-44-02](https://user-images.githubusercontent.com/26003928/57521796-2cf5c300-735c-11e9-8ded-c4ac9cc722b7.png)

When you create a new instance of generics type whose namespace does not have any periods (like `<string>`, `<int>`, or `<FooBarList>`), `List<string>` is colored with blue.

![Screenshot from 2019-05-10 19-45-01](https://user-images.githubusercontent.com/26003928/57521799-2cf5c300-735c-11e9-8439-364636646c74.png)

However, when you create a new instance of generics type whose namespace has periods (like `IBus.Bus` or `FooBarList.FooBarListRow`), the last `>` is not colored correctly.

**Comment by thiagojedi** [comment]
Thanks!

I'll have a look on it this weekend.

**Comment by thiagojedi** [comment]
Fixed in 0.3.3. Thanks.
