### ISSUE TITLE
cant build

### ISSUE THREAD

**Issue by gavr123456789** [thiagoabreu/vala-code#14]
after "Hit F5 in VS Code " i get that 
![image](https://user-images.githubusercontent.com/30507409/57892355-4e1c4f00-7847-11e9-978a-706c99cc70a4.png)  

and that 
![image](https://user-images.githubusercontent.com/30507409/57892365-57a5b700-7847-11e9-8df3-6e2e0ba37123.png)

**Comment by thiagojedi** [comment]
Just updated the vscode's files for the new format. Let me know if you still have problem running the extension in development mode.
