### ISSUE TITLE
How to use libvala 

### ISSUE THREAD

**Issue by gavr123456789** [thiagoabreu/vala-code#15]
Hello im newbie in all this vls and vala, in the description of the plugin when installing it from extensions vs code states that it is better to use libvala for autocomplete and better forming.
So, how to do it?

**Comment by thiagojedi** [comment]
LibVala is the library used by Vala's compiler (`valac`) to parse the source code so it can manipulate it.

Both @benwaffle ([here](https://github.com/benwaffle/vala-language-server))  and @davidmhewitt ([here](https://github.com/davidmhewitt/vala-language-server)) are already working on editor-agnostic autocomplete solutions using libvala. So I suggest you contribute with their projects or at least read their code as you may learn a lot about libvala's usage.

The library's documentation can be found here: https://benwaffle.github.io/vala-language-server/vala/index.htm
