### ISSUE TITLE
problem matcher gets file not found

### ISSUE THREAD

**Issue by SingingBush** [thiagoabreu/vala-code#5]
in `vala-code/package.json` the problemMatcher uses `"fileLocation": "absolute"` which ends up in file not found when clicking on the problem. I think it should be:

```json
"fileLocation": ["relative", "${workspaceRoot}"],
```

**Comment by SingingBush** [comment]
can confirm that setting it as decribed above fixes bug. I set a problem matcher locally using:

```json
            "problemMatcher": {
                "owner": "vala",
                "fileLocation": ["relative", "${workspaceRoot}"],
                "pattern": {
                    "regexp": "^(.*):(\\d+)\\.(\\d+)-(\\d+)\\.(\\d+):\\s+(warning|error):\\s+(.*)$",
                    "file": 1,
                    "line": 2,
                    "column": 3,
                    "endLine": 4,
                    "endColumn": 5,
                    "severity": 6,
                    "message": 7
                }
            }
```

**Comment by thiagojedi** [comment]
@dlech can you have a look on this?

**Comment by dlech** [comment]
I think it is possible to define a `problemPattern` in the extension rather than a `problemMatcher`. This way the use can specify the `"fileLocation"`. It is currently `"absolute"`, which I suspect is what is causing the problem.

**Comment by SingingBush** [comment]
just changing from absolute to relative will be fine
