### ISSUE TITLE
problem matcher doesn't find deprecation warnings

### ISSUE THREAD

**Issue by SingingBush** [thiagoabreu/vala-code#6]
the regexp `^(.*):(\\d+)\\.(\\d+)-(\\d+)\\.(\\d+):\\s+(warning|error):\\s+(.*)$` is doing fine for finding error messages from valac but it doesn't do so well at warnings. I got the the following warning about a deprecation and the format of the line is quite different: `/home/singingbush/gtkproject/src/myapp-gtk.vala:22:2: warning: ‘gtk_color_button_set_rgba’ is deprecated: Use 'gtk_color_chooser_set_rgba' instead`

the following should work in this scenario `^(.*):(\d+):(\d+):\s+(warning):\s+(.*)$`

perhaps instead of just having a $valac problemMatcher there could be $valac-errors and $valac-warnings. That also gives the user more control about what they want to match on: `"problemMatcher": [ "$valac-errors", "$valac-warnings" ]`

**Comment by dlech** [comment]
I don't see a need for have two separate matchers. Here is a one-liner that should work for both cases. Besides, I think most warnings match the current regex, e.g.

    /home/david/work/ev3dev-dpkg/conosle-runner/src/client.vala:59.5-57.5: warning: main blocks are experimental

I think I have a regex that fits both cases: https://regex101.com/r/rCnJXa/3

I'm not sure what the `2` is after the `22` in your error message. I presume `22` is the line number. Is the `2` the column number maybe?

**Comment by SingingBush** [comment]
I agree that one regex is better if it works in all scenarios.

Although the regex is matching on various groups in the deprecation message it doesn't get picked up and displayed in the _problem_ tab like other messages do.

Could this be because there are less match groups for a deprecation message?

I'm not sure what the 2 was, if it's the column then it's picking up on white space as the code is indented 8 columns in on that line.
