### ISSUE TITLE
Jump to Definition

### ISSUE THREAD

**Issue by jakejarrett** [thiagoabreu/vala-code#9]
This is something that'd be immensely useful when developing.

[Here is an implementation for the PHP plugin](https://github.com/felixfbecker/php-language-server/pull/49)

Happy to help if you require any help with this.

**Comment by thiagojedi** [comment]
Hi @jakejarrett 

Yes. It's useful, indeed. For this to work, we need a language server for Vala. I've been keeping an eye in this one: https://github.com/benwaffle/vala-language-server

In that repository, @benwaffle is working the Language Server Protocol. Which is rather simple. If you want to help, you should have a look on the [Language Server documentation](https://github.com/Microsoft/language-server-protocol/blob/master/protocol.md) and see if you can wire the Libvala library. Libvala already has a lot of nice features like the one you mentioned.
